### ISSUE TITLE
Ability to specify host for cloudflared

### ISSUE THREAD

**Issue by BluDood** [SignTools/SignTools#412]
!! Please fill in this template, DO NOT ignore or delete it. !!

**I tried basic troubleshooting first**

- [x] Updated **both** [SignTools](https://github.com/SignTools/SignTools) **and** the builder ([SignTools-CI](https://github.com/SignTools/SignTools-CI) or [SignTools-Builder](https://github.com/SignTools/SignTools-Builder)) to the latest version
- [x] Read through the [FAQ page](https://github.com/SignTools/SignTools/blob/master/FAQ.md)

**Describe the bug**
I'm trying to run SignTools and a CloudFlare tunnel inside docker compose, but SignTools is hardcoded to only look for cloudflared on localhost. Therefore it would be very useful to be able to specify the host used for connecting to the cloudflared metrics endpoint.

**To reproduce**
In my case, I wrote a simple compose project as follows:
```yaml
version: '3.8'

services:
  signtools:
    image: signtools/signtools
    volumes:
      - './signer-cfg.yml:/signer-cfg.yml'
      - './data:/data'
  cloudflared:
    image: cloudflare/cloudflared
    command: tunnel -url http://signtools:8080 -metrics 0.0.0.0:51881
```
By opening the generated tunnel URL, I can access the web interface just fine. However, this does not work once I try to sign the application as it has to send data back to the public endpoint. I could manually specify the URL inside signer-cfg.yml, but since the functionality is already built-in it would be nice to have an extra option to specify a custom host for cloudflared. For example:
`SignTools -cloudflared-host cloudflared -cloudflared-port 51881`
or simply:
`SignTools -cloudflared-host cloudflared:51881`

I imagine it wouldn't be too hard to add some changes [here (for the CLI parameter)](https://github.com/SignTools/SignTools/blob/20fc4bfbc0d33b051ef9fc6f7e7f4d1660237494/main.go#L67) and [here (to change the host from localhost to whatever is specified)](https://github.com/SignTools/SignTools/blob/20fc4bfbc0d33b051ef9fc6f7e7f4d1660237494/src/tunnel/cloudflare.go#L20). I don't know Go too well, but if help is needed I can see what I can do.

**Expected behavior**

Being able to specify the full host for the cloudflared endpoint / host, and therefore making it easier to run SignTools in a Docker Compose project.

**System configuration**

- SignTools version: 3.0.2
- Installation type: Docker / cloudflared
- Operating System: Windows
- Builder type: SignTools-CI
- Builder version: 13250eb
